services:
  server:
    build: .
    env_file:
      - path: ./.env
        required: true
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_REALM=${JWT_REALM}
      - JWT_ISSUER=${JWT_ISSUER}
      - KTOR_PORT=${KTOR_PORT}
      - DB_ENGINE=${DB_ENGINE}

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=portfolio_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s